[package]
name = "roll"
version = "0.1.2"
authors = ["Keith Yager <kyager@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
structopt = "0.3.13"